spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/book_manage
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml