spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/book_manage
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml